### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'node_from_json'

### ISSUE THREAD

**Issue by almereyda** [fiduswriter/fiduswriter#1097]
After a recent upgrade from Fidus Writer 3.8.8 to 3.9.2 and successfully running `fiduswriter migrate`, no Websocket connection can be established anymore.

The server outputs:

```
ERROR:tornado.application:Uncaught exception GET /ws/document/1/ (0.0.0.0)                        
HTTPServerRequest(protocol='https', host='writer.allmende.io', method='GET', uri='/ws/document/1/', version='HTTP/1.1', remote_ip='0.0.0.0')
Traceback (most recent call last):                                                                           
  File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)                                                                     
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/base/ws_handler.py", line 102, in on_message
    self.handle_message(message)                                                                          
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/document/ws_views.py", line 230, in handle_message
    self.subscribe_doc(connection_count)                                                         
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/document/ws_views.py", line 88, in subscribe_doc
    content                                                                                          
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/document/prosemirror.py", line 23, in from_json
    return Node.from_json(schema, json)                                                               
  File "/usr/local/lib/python3.6/dist-packages/prosemirror/model/node.py", line 268, in from_json
    content = Fragment.from_json(schema, json_data.get("content")) 
  File "/usr/local/lib/python3.6/dist-packages/prosemirror/model/fragment.py", line 210, in from_json
    return cls([schema.node_from_json(item) for item in value])                                                                                  
  File "/usr/local/lib/python3.6/dist-packages/prosemirror/model/fragment.py", line 210, in <listcomp>
    return cls([schema.node_from_json(item) for item in value])                                 
AttributeError: 'NoneType' object has no attribute 'node_from_json'
```

while the client only reports repeating GET Websocket requests to `/ws/document/1/`, that are answered with an HTTP 101 response containing the `Connection: Upgrade` header.

I suspect the migration was incomplete, and the documents have not been upgraded to a schema that supports the new offline merging, as it is the prosemirror module that cannot reconstruct the document with the source data being a `NoneType`.

Else database access and login do work.

**Comment by johanneswilm** [comment]
Hey @almereyda ,
I don't know exactly what this is about, but it looks like it is connected to us using prosemirror-py for merged on the server side. It seems like the schema copying is not working the way we envisioned. I don't think anything about the migrations is working incorrectly.

While trying to figure out why this isn't working for your setup (checkout the management command `./manage export_schema`),  you can turn prosemirror-py off by setting JSONPATCH = True in the configuration.py file. In fact, that should be the default, so I'm not sure how you could end up with this.

The easiest way of running FW is to just run it on an Ubuntu server with the Ubuntu Snap package. That is generally working without any hitches.

**Comment by johanneswilm** [comment]
@almereyda Could check whether this file exists: static-libs/json/schema.json ?

**Comment by johanneswilm** [comment]
And could you also let me know what system you are running this on and if you did any modifications to the code?

**Comment by almereyda** [comment]
Thank you for the detailed response. I couldn't come back to this until now. Of course this is an unsupported, inofficial Docker port https://github.com/allmende/docker-fiduswriter that allows me to run into these kinds of edge cases. The only adaptations happen within `configuration.py`, which indeed did not know a JSONPATCH setting. In configuration I'm orienting myself in https://github.com/fiduswriter/fiduswriter/blob/master/fiduswriter/configuration.py-default which also doesn't contain it.

Please find the requested outputs here:

```py
fiduswriter@c87bf90f25f2:/fiduswriter$ fiduswriter export_schema
Copying document schema
Traceback (most recent call last):
  File "/usr/local/bin/fiduswriter", line 8, in <module>
    sys.exit(entry())
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/manage.py", line 93, in entry
    inner(os.getcwd())
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/manage.py", line 85, in inner
    execute_from_command_line(sys_argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/document/management/commands/export_schema.py", line 33, in handle
    js = js_file.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 242922: ordinal not in range(128)
```

The `schema.json` file is not present there, but the directory. After running `fiduswriter setup`, the process outputs `Copying document schema`, but it doesn't tell where to, or if it worked.

The `AttributeError: 'NoneType' object has no attribute 'node_from_json'` error also fires with JSONPATCH = True.

All this was on version 3.9.2. Version 3.9.19 tells me this upon trying to run the startup migration:

```py
Operations to perform:                                            
  Apply all migrations: account, admin, auth, avatar, bibliography, book, contenttypes, document, feedback, flatpages, sessions, sites, socialaccount, style, user, usermedia
Running migrations:                                            
Traceback (most recent call last):                                                                     
  File "/usr/local/bin/fiduswriter", line 8, in <module>       
    sys.exit(entry())                                                                                        
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/manage.py", line 99, in entry
    inner(os.getcwd())
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/manage.py", line 91, in inner
    execute_from_command_line(sys_argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/base/management/commands/setup.py", line 44, in handle
    call_command("migrate")
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/commands/migrate.py", line 245, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.6/dist-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/dist-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.6/dist-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.6/dist-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/document/migrations/0007_fix_fidus_3_3.py", line 183, in update_documents
    update_revision_zip(revision.file_object, revision.file_name)
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/document/migrations/0007_fix_fidus_3_3.py", line 136, in update_revision_zip
    with zipfile.ZipFile(file_field.open(), 'r') as zin:
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/fields/files.py", line 74, in open
    self.file = self.storage.open(self.name, mode)
  File "/usr/local/lib/python3.6/dist-packages/django/core/files/storage.py", line 36, in open
    return self._open(name, mode)
  File "/usr/local/lib/python3.6/dist-packages/django/core/files/storage.py", line 231, in _open
    return File(open(self.path(name), mode))
FileNotFoundError: [Errno 2] No such file or directory: '/fiduswriter/media/document-revisions/1_d71xNvu.fidus'
  Applying document.0007_fix_fidus_3_3...
```

despite the file being there. Running `fiduswriter migrate` manually helped getting past this error. Gladly `export_json` has a new error:

```py
Traceback (most recent call last):
  File "/usr/local/bin/fiduswriter", line 8, in <module>
    sys.exit(entry())
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/manage.py", line 99, in entry
    inner(os.getcwd())
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/manage.py", line 91, in inner
    execute_from_command_line(sys_argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/document/management/commands/export_schema.py", line 31, in handle
    "static-transpile/js/schema_export.js"
FileNotFoundError: [Errno 2] No such file or directory: '/fiduswriter/static-transpile/js/schema_export.js'
```

Running `fiduswriter transpile` then to generate `static-transpile` errors out similarily as `export_schema` did previously:

```py
Time spent transpiling: 40 seconds
Copying document schema
Traceback (most recent call last):
  File "/usr/local/bin/fiduswriter", line 8, in <module>
    sys.exit(entry())
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/manage.py", line 99, in entry
    inner(os.getcwd())
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/manage.py", line 91, in inner
    execute_from_command_line(sys_argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/npm_mjs/management/commands/transpile.py", line 327, in handle
    signals.post_transpile.send(sender=None)
  File "/usr/local/lib/python3.6/dist-packages/django/dispatch/dispatcher.py", line 179, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.6/dist-packages/django/dispatch/dispatcher.py", line 179, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/document/apps.py", line 8, in export_schema
    call_command("export_schema")
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/fiduswriter/document/management/commands/export_schema.py", line 33, in handle
    js = js_file.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 244267: ordinal not in range(128)
```

Now I see I might also need to take https://github.com/fiduswriter/fiduswriter/blob/master/fiduswriter/base/default_settings.py into account. Additionally to that `https://github.com/fiduswriter/fiduswriter/blob/master/fiduswriter/base/webpack.config.template.js` was expected to live in `/data` which, with it actually living right next to `default_settings.py`, allows to conclude that `/usr/local/lib/python3.6/dist-packages/fiduswriter/base/` is not correctly fetched when running `fiduswriter`....

Thanks a lot for taking the time to look into this. Please tell me if you have any further ideas. I'm also open to closing here, since these seem to be mainly packaging errors related with the Docker port, which can also be discussed in issues over there.

---

In fact, as it turns out, updating the base image and Fiduswriter to their latest stable releases helped resolve this issue.

I'd think Node.js 10 was too old for being able to handle all the NPM transpile actions.

- https://github.com/moritzfl/docker-fiduswriter/pull/10
