### ISSUE TITLE
Fiduswriter stopped working Ubuntu 20.04

### ISSUE THREAD

**Issue by l-fura** [fiduswriter/fiduswriter#1255]
Hi, 

the fiduswriter server worked for me for several months on a virtual machine running Ubuntu 20.04. Today it stopped working, i.e. the login page loads, but I can't log in (sometimes after a `snap restart fiduswriter` it succeeds, but after logging out it is no longer possible to log in). 
In addition, when I type `fiduswriter.createsuperuser` in the terminal, I get this list of errors (below). Previously, everything worked fine. 
It looks like there is some problem with the database connection. Does anyone know how to fix this?

```
Traceback (most recent call last):
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1040, 'Too many connections')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/snap/fiduswriter/1287/bin/fiduswriter", line 8, in <module>
    sys.exit(entry())
             ^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/fiduswriter/manage.py", line 86, in entry
    inner(os.getcwd())
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/fiduswriter/manage.py", line 81, in inner
    execute_from_command_line(sys_argv)
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 88, in execute
    return super().execute(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/core/management/base.py", line 447, in execute
    self.check_migrations()
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/core/management/base.py", line 564, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
       ^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/db/backends/base/base.py", line 323, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/db/backends/base/base.py", line 299, in _cursor
    self.ensure_connection()
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/db/backends/base/base.py", line 281, in ensure_connection
    with self.wrap_database_errors:
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/fiduswriter/1287/lib/python3.11/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1040, 'Too many connections')
```

**Comment by johanneswilm** [comment]
Hey @l-fura ,
there has been no recenty update. It sounds like there are too many connections to your database. Have you checked whether your harddrive has run out of space?

**Comment by l-fura** [comment]
It still has almost 10 GB of free space.

**Comment by johanneswilm** [comment]
Something seems to be accessing your database. Have you tried restarting?

**Comment by l-fura** [comment]
Yeah, I tried and it's stille the same problem.

**Comment by johanneswilm** [comment]
@l-fura Are you running anything else on the same server? Is it possible for you to update the Ubuntu to 22.04?

**Comment by johanneswilm** [comment]
@l-fura Also, what do you get if you run:

```sudo fiduswriter.mysql-client```

And inside mysql then:

```
show processlist;
```

You can also see how long it waits for timeout of sleeping connections in SQL:

```

**Comment by l-fura** [comment]
Thank you @johanneswilm. It's working now. 

mysql> show processlist;
+--------+-----------------+-----------+-------------+---------+-------+------------------------+------------------+
| Id     | User            | Host      | db          | Command | Time  | State                  | Info             |
+--------+-----------------+-----------+-------------+---------+-------+------------------------+------------------+
|      5 | event_scheduler | localhost | NULL        | Daemon  | 72429 | Waiting on empty queue | NULL             |
| 346672 | fiduswriter     | localhost | fiduswriter | Sleep   |  7716 |                        | NULL             |
| 346673 | fiduswriter     | localhost | fiduswriter | Sleep   |  7436 |                        | NULL             |
| 346674 | fiduswriter     | localhost | fiduswriter | Sleep   |  7290 |                        | NULL             |
| 346675 | fiduswriter     | localhost | fiduswriter | Sleep   |  7119 |                        | NULL             |
| 346676 | fiduswriter     | localhost | fiduswriter | Sleep   |  5309 |                        | NULL             |
| 346677 | fiduswriter     | localhost | fiduswriter | Sleep   |  5308 |                        | NULL             |
| 346678 | root            | localhost | NULL        | Query   |     0 | init                   | show processlist |
+--------+-----------------+-----------+-------------+---------+-------+------------------------+------------------+
8 rows in set (0.04 sec)
