### ISSUE TITLE
SyntaxError in base/management/commands/bundle_katex.py

### ISSUE THREAD

**Issue by rhunwicks** [fiduswriter/fiduswriter#145]
I am trying to do a fresh install of Fiduswriter. When I run `python manage.py init` I get:

```
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/roger/.virtualenvs/fiduswriter/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/roger/.virtualenvs/fiduswriter/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/roger/.virtualenvs/fiduswriter/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/roger/.virtualenvs/fiduswriter/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/roger/git/fiduswriter/base/management/commands/init.py", line 35, in handle
    call_command("bundle_katex")
  File "/home/roger/.virtualenvs/fiduswriter/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 99, in call_command
    command = load_command_class(app_name, name)
  File "/home/roger/.virtualenvs/fiduswriter/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/roger/git/fiduswriter/base/management/commands/bundle_katex.py", line 17
    if out_file.split(.)[-1].lower()== 'css':
                      ^
SyntaxError: invalid syntax
```

I guess that should be:

```python
if out_file.split('.')[-1].lower()== 'css':
```

**Comment by johanneswilm** [comment]
Yes, thanks!
