### ISSUE TITLE
Error on new build (ubuntu 14.04), unable to edit document

### ISSUE THREAD

**Issue by zeigerpuppy** [fiduswriter/fiduswriter#173]
On a new build (using the standard install procedure), accessing the site returns the following error in the console

```
ERROR:tornado.general:Could not open static file None
ERROR:javascript_error:Got error:
        details: https://fidus.greenant.net/static/js/editor.es5.js:32866: RangeError: Index 1 out of range for <paragraph>
        context: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2
```

There was a build error when installing but the install did complete
```
prebuild WARN install Prebuilt binaries for node version v6.1.0 are not available
Package fuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `fuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fuse' found
gyp: Call to 'pkg-config fuse --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
prebuild ERR! configure error
prebuild ERR! stack Error: `gyp` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onCpExit (/home/xx/Downloads/fiduswriter/node_modules/prosemirror/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! stack     at emitTwo (events.js:106:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:191:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
prebuild ERR! not ok
prebuild ERR! build Error: `gyp` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onCpExit (/home/xx/Downloads/fiduswriter/node_modules/prosemirror/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
npm WARN install:fuse-bindings@2.8.1 fuse-bindings@2.8.1 install: `prebuild --install`
npm WARN install:fuse-bindings@2.8.1 Exit status 2
```

**Comment by johanneswilm** [comment]
And this is without running any type of proxy, correct? Just following the install instructions and nothing more, right?

**Comment by zeigerpuppy** [comment]
Working when not proxied,
any instructions on how to proxy?

**Comment by johanneswilm** [comment]
Sorry, then this is not a bug. You can either figure it out yourself or hire my services at a rate of 150 Euros/h to debyg your setup. Sorry - hope you figure it out!.
