### ISSUE TITLE
fiduswriter stopped working with "UncompressableFileError"

### ISSUE THREAD

**Issue by zeigerpuppy** [fiduswriter/fiduswriter#175]
fiduswriter was working from a new install with some minor config changes (setting site root and SMTP settings) it has now stopped working.
While 2 users were testing and trying equations, it returned the following error and returns a 500 error even when restarted

```
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/fiduswriter/document/views.py", line 100, in index
    response)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 99, in render_compressed
    cache_key, cache_content = self.render_cached(compressor, kind, mode)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 78, in render_cached
    cache_key = get_templatetag_cachekey(compressor, mode, kind)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/compressor/cache.py", line 104, in get_templatetag_cachekey
    "templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/compressor/base.py", line 195, in cachekey
    [self.content] + self.mtimes).encode(self.charset), 12)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/compressor/base.py", line 189, in mtimes
    for kind, value, basename, elem in self.split_contents()
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/compressor/js.py", line 19, in split_contents
    filename = self.get_filename(basename)
  File "/opt/fiduswriter/venv/local/lib/python2.7/site-packages/compressor/base.py", line 157, in get_filename
    self.finders and " or with staticfiles." or "."))
UncompressableFileError: 'js/contact-helpers.js' could not be found in the COMPRESS_ROOT '/tmp/django-static' or with staticfiles.
ERROR:tornado.access:500 GET / (49.183.191.219) 10286.54ms
```

**Comment by johanneswilm** [comment]
@zeigerpuppy Thanks! You turned compression on, which is when this stopped working for you. Please update to latest github and run ```./manage transpile``` before restarting your server.

**Comment by zeigerpuppy** [comment]
thanks, that fixed it.
