### ISSUE TITLE
install of requirements

### ISSUE THREAD

**Issue by jucajuca** [fiduswriter/fiduswriter#459]
Hi, I'm getting the following error when trying to install fidus writer (in a raspberry pi)

The /root/.pip/pip.log file basically says that it can't find future 0.16.0 (404 error)

any ideas why is this happening?

**$ pip install -r requirements.txt**
```
Requirement already satisfied (use --upgrade to upgrade): Django==1.11 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 1))
...
...
Requirement already satisfied (use --upgrade to upgrade): setuptools==35.0.2 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 11))
Downloading/unpacking future==0.16.0 (from -r requirements.txt (line 12))
  Downloading future-0.16.0.tar.gz (824kB): 824kB downloaded
  Running setup.py (path:/tmp/pip-build-tHkwOa/future/setup.py) egg_info for package future
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "/var/www/fiduswriter/venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/var/www/fiduswriter/venv/local/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/var/www/fiduswriter/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 70, in <module>
        import packaging.version
    ImportError: No module named packaging.version
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "/var/www/fiduswriter/venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>

    import setuptools.version

  File "/var/www/fiduswriter/venv/local/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>

    import pkg_resources

  File "/var/www/fiduswriter/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 70, in <module>

    import packaging.version

ImportError: No module named packaging.version

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-tHkwOa/future
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by jucajuca** [comment]
can be solved like so:

sudo ./venv/bin/pip pip install -r requirements.txt

I think that the problem is that the folder was under /var/www which belongs to the user www-data.

This means that the installation of fidus should initially be done for example at the home directory.

**Comment by johanneswilm** [comment]
Hey, sorry, I have been offline. You fixed this yourself?

**Comment by jucajuca** [comment]
yes, thank you.
One thing here is that you have to make sure that pip is up-to-date, because older versions of pip will not install "future"

so: pip install --upgrade pip
