### ISSUE TITLE
Install Error on Ubuntu 18.04

### ISSUE THREAD

**Issue by conloos** [fiduswriter/fiduswriter#897]
Hi,

i tried to install Fidus Writer at a fresh ubuntu 18.04 in a lxc container by using the instructions from the wiki (https://github.com/fiduswriter/fiduswriter/wiki/Installation-on-Ubuntu-18.04).

At the point 6 "./manage.py init" i get this exception:

`Traceback (most recent call last):
  File "./manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/fiduswriter/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/fiduswriter/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/fiduswriter/venv/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/fiduswriter/venv/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/opt/fiduswriter/fiduswriter/base/management/commands/init.py", line 50, in handle
    call_command("collectstatic", interactive=False)
  File "/opt/fiduswriter/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/opt/fiduswriter/venv/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/opt/fiduswriter/fiduswriter/base/management/commands/collectstatic.py", line 10, in handle
    return super(Command, self).handle(*args, **options)
  File "/opt/fiduswriter/venv/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
    collected = self.collect()
  File "/opt/fiduswriter/venv/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 105, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/opt/fiduswriter/venv/lib/python3.6/site-packages/django/contrib/staticfiles/finders.py", line 125, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/opt/fiduswriter/venv/lib/python3.6/site-packages/django/contrib/staticfiles/utils.py", line 23, in get_files
    directories, files = storage.listdir(location)
  File "/opt/fiduswriter/venv/lib/python3.6/site-packages/django/core/files/storage.py", line 313, in listdir
    for entry in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/fiduswriter/fiduswriter/static-libs'
`

`
# ls -l 

-rw-r--r-- 1 root root    350 Sep 17 12:48 AUTHORS
-rw-r--r-- 1 root root    128 Sep 17 12:45 CONTRIBUTING.md
-rw-r--r-- 1 root root  34500 Sep 17 12:45 LICENSE
-rwxr-xr-x 1 root root   1281 Sep 17 12:48 README.md
drwxr-xr-x 1 root root    380 Sep 17 12:50 base
drwxr-xr-x 1 root root    174 Sep 17 12:50 bibliography
drwxr-xr-x 1 root root    128 Sep 17 12:50 browser_check
-rw-r--r-- 1 root root   3010 Sep 17 12:48 configuration.py-default
-rw-r--r-- 1 root root     59 Sep 17 12:48 dev-requirements.txt
drwxr-xr-x 1 root root    244 Sep 17 12:50 document
drwxr-xr-x 1 root root    158 Sep 17 12:50 feedback
drwxr-xr-x 1 root root    394 Sep 17 12:50 fiduswriter
-rw-r--r-- 1 root root 798720 Sep 17 13:02 fiduswriter.sql
drwxr-xr-x 1 root root     64 Sep 17 12:50 fixturemedia
drwxr-xr-x 1 root root     38 Sep 17 12:48 locale
-rwxr-xr-x 1 root root   1031 Sep 17 12:48 manage.py
drwxr-xr-x 1 root root     60 Sep 17 12:50 media
drwxr-xr-x 1 root root     56 Sep 17 12:50 menu
-rw-r--r-- 1 root root     20 Sep 17 12:48 mysql-requirements.txt
drwxr-xr-x 1 root root  12358 Sep 17 12:58 node_modules
-rw-r--r-- 1 root root   3878 Sep 17 12:56 package.json
-rw-r--r-- 1 root root     16 Sep 17 12:48 postgresql-requirements.txt
-rwxr-xr-x 1 root root    265 Sep 17 12:48 requirements.txt
drwxr-xr-x 1 root root     24 Sep 17 12:58 static-transpile
drwxr-xr-x 1 root root    114 Sep 17 12:50 style
drwxr-xr-x 1 root root    132 Sep 17 12:48 test
-rw-r--r-- 1 root root     37 Sep 17 12:48 test-requirements.txt
drwxr-xr-x 1 root root     32 Sep 17 12:45 travis
drwxr-xr-x 1 root root    232 Sep 17 12:50 user
drwxr-xr-x 1 root root    174 Sep 17 12:50 usermedia
-rw-r--r-- 1 root root      7 Sep 17 12:48 version.txt
`
I tried it two times so it is reproducible.

Thanks Frank

**Comment by johanneswilm** [comment]
Hey @conloos this error seems to be referring to the 3.6.x instructions. The instructions have since been updated for 3.6. Please retry with FW 3.7 and the new instructions.
